name: ct_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pydicom
  - simpleitk
  - scipy
  - scikit-image
  - jupyterlab
  - ipykernel
  - itk
